export const ENV = {
  SALLA_CLIENT_ID: process.env.SALLA_CLIENT_ID,
  SALLA_CLIENT_SECRET: process.env.SALLA_CLIENT_SECRET,
  SALLA_WEBHOOK_SECRET: process.env.SALLA_WEBHOOK_SECRET,

  META_ACCESS_TOKEN: process.env.META_ACCESS_TOKEN,
  META_PHONE_ID: process.env.META_PHONE_ID,

  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY
};
